# Generated by Django 3.1.3 on 2021-01-18 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0004_auto_20210117_1038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userquestion',
            old_name='question_id',
            new_name='question',
        ),
    ]
