# Generated by Django 3.1.3 on 2021-01-21 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0005_auto_20210118_0853'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
