# Generated by Django 3.1.3 on 2021-02-07 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0006_auto_20210121_2015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='section',
        ),
    ]
