# Generated by Django 3.1.3 on 2021-02-07 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0007_remove_category_section'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Section',
        ),
    ]
